### ISSUE TITLE
Use bootstrap or material

### ISSUE THREAD

**Issue by xgrommx** [Cmdv/React-RxJS#1]
Hi @Cmdv I think will be better use http://react-bootstrap.github.io or http://material-ui.com instead pure bootstrap.

**Comment by Cmdv** [comment]
@xgrommx yeah definatelly if you'd like to implement it do a pull request and I'll merge it in. (material-ui looks really nice) I put some styling in there to get the ball rolling.

**Comment by Cmdv** [comment]
@xgrommx Having thought about it a little more should we keep away from React specific styling/components? 
People might want to implement their own css also, it may be too confusing for first time viewers in the master branch but by all means make a branch and we can implement it there and give people the option to use that branch :)

**Comment by xgrommx** [comment]
@Cmdv You are right =) I agree with you
