### ISSUE TITLE
jspm

### ISSUE THREAD

**Issue by giltig** [Cmdv/React-RxJS#10]
Hi why don't you use jspm (which is easier for dev) instead of webpack?

**Comment by Cmdv** [comment]
Hi, you can add all sorts to webpack, like babel for the ES6 compiling, live reload, sass, etc... but I didn't want to make the compiling process too big like that people can put in their own preferred compiler.

All it does right now is compile/watch index.js converts with babel and puts it into -->  .build/index.js

So if people want to put css or have Grunt / Gulp do the compilation, or JSPM then they can without too much hassle.
