### ISSUE TITLE
Falcor Integration?

### ISSUE THREAD

**Issue by a9a4k** [Cmdv/React-RxJS#16]
Could you please add a falcor to the stack. Really interested on how it will play out. I am trying currently to make a simple todo app, but my implementation seems weird. Or can you give directions on how you would go about adding falcor to your example and I will go from there?

**Comment by Cmdv** [comment]
Hi, I've not been very active on this and hadn't planned to put Falcor in but do you have a link to what you are working on I could try help there? @almasakchabayev

**Comment by a9a4k** [comment]
@Cmdv Cool! I have just started playing around with falcor and rxjs. I will add you as a collaborator to my todo app :) https://github.com/almasakchabayev/react-rx-falcor

**Comment by Cmdv** [comment]
Ok will see what i can do, but in al honesty I've not used Falcor yet so will see what can be worked out :+1:

**Comment by a9a4k** [comment]
Great. I am sure you will grasp it in no time :) very easy stuff compared to relay
